# ===========================================
# КОНФИГУРАЦИЯ РИСК-МЕНЕДЖМЕНТА
# Vortex Trading Bot Risk Management Settings
# ===========================================

# Основные настройки риск-менеджмента
enabled: true                    # Включить/выключить риск-менеджмент
currency: "USDT"                 # Базовая валюта для расчетов
persist_runtime_updates: true    # Сохранять изменения настроек в файл

# ===========================================
# ДНЕВНЫЕ ЛИМИТЫ (UTC)
# ===========================================
daily:
  # Максимальный абсолютный убыток за день (USDT)
  max_abs_loss: 500.0            # Если убыток превысит 500 USDT - торговля остановится
  
  # Максимальная просадка за день (%)
  max_drawdown_pct: 5.0           # Если просадка превысит 5% - торговля остановится
  
  # Максимальное количество сделок за день
  max_trades: 20                  # Не более 20 сделок в день
  
  # Время сброса дневных счетчиков (UTC)
  reset_time_utc: "00:00"         # Полночь по UTC

# ===========================================
# НЕДЕЛЬНЫЕ ЛИМИТЫ
# ===========================================
weekly:
  # Максимальный абсолютный убыток за неделю (USDT)
  max_abs_loss: 1500.0            # Если недельный убыток > 1500 USDT - стоп
  
  # Максимальная просадка за неделю (%)
  max_drawdown_pct: 10.0          # Если недельная просадка > 10% - стоп
  
  # День сброса недельных счетчиков (UTC)
  reset_dow_utc: "MONDAY"         # Сброс каждый понедельник

# ===========================================
# ЛИМИТЫ ПОЗИЦИЙ
# ===========================================
position:
  # Максимальный риск на одну позицию (% от капитала)
  max_risk_pct: 2.0               # Увеличено с 1.0 до 2.0 для нормальной работы
  
  # Максимальное плечо
  max_leverage: 10                # Максимум 10x плечо
  
  # Максимальное количество одновременных позиций
  max_concurrent_positions: 5      # Не более 5 позиций одновременно
  
  # Максимальный размер одной позиции (% от капитала)
  max_position_size_pct: 10.0      # Не более 10% капитала на одну позицию
  
  # Минимальный размер позиции (USDT)
  min_position_size: 10.0          # Минимум 10 USDT на позицию

# ===========================================
# CIRCUIT BREAKER (Аварийная остановка)
# ===========================================
circuit_breaker:
  # Жесткая остановка при превышении лимитов
  hard_stop: true                  # true = полная остановка, false = только алерт
  
  # Время "охлаждения" после срабатывания (минуты)
  cool_down_minutes: 120           # 2 часа паузы после аварийной остановки
  
  # Условия срабатывания circuit breaker
  triggers:
    # Количество убыточных сделок подряд
    consecutive_losses: 5           # 5 убытков подряд = стоп
    
    # Быстрая потеря капитала (% за период)
    rapid_loss_pct: 3.0             # Потеря 3% за...
    rapid_loss_minutes: 60          # ...60 минут = стоп
    
    # Критическая просадка
    critical_drawdown_pct: 15.0     # При просадке 15% = немедленный стоп

# ===========================================
# ЗАЩИТА ОТ ПЕРЕТОРГОВКИ
# ===========================================
overtrading_protection:
  # Минимальный интервал между сделками (секунды)
  min_trade_interval: 60           # Минимум 60 секунд между сделками
  
  # Максимум сделок в час
  max_trades_per_hour: 5           # Не более 5 сделок в час
  
  # Пауза после серии убытков
  pause_after_losses: 3            # После 3 убытков подряд...
  pause_duration_min: 30           # ...пауза 30 минут

# ===========================================
# АДАПТИВНОЕ УПРАВЛЕНИЕ РИСКАМИ
# ===========================================
adaptive_risk:
  enabled: false                   # Включить адаптивную систему
  
  # Корректировка размера позиций на основе результатов
  performance_based_sizing:
    # После прибыльной сделки
    win_size_increase: 1.1          # Увеличить на 10%
    
    # После убыточной сделки
    loss_size_decrease: 0.9         # Уменьшить на 10%
    
    # Лимиты корректировки
    max_adjustment: 2.0             # Максимум x2 от базового размера
    min_adjustment: 0.5             # Минимум x0.5 от базового размера
  
  # Динамические стоп-лоссы
  dynamic_stops:
    enabled: false
    
    # В зависимости от волатильности
    volatility_multiplier: 1.5      # ATR * 1.5 для стоп-лосса
    
    # Минимальный и максимальный стоп
    min_stop_pct: 0.5               # Минимум 0.5% стоп
    max_stop_pct: 5.0               # Максимум 5% стоп

# ===========================================
# МОНИТОРИНГ И АЛЕРТЫ
# ===========================================
monitoring:
  # Предупреждения при приближении к лимитам
  warning_thresholds:
    # % от лимита для предупреждения
    daily_loss_warning: 80          # Алерт при 80% от дневного лимита
    weekly_loss_warning: 70         # Алерт при 70% от недельного лимита
    position_count_warning: 80      # Алерт при 80% от макс. позиций
  
  # Логирование
  log_all_trades: true              # Логировать все сделки
  log_risk_events: true             # Логировать события риск-менеджмента
  log_level: "INFO"                 # DEBUG, INFO, WARNING, ERROR

# ===========================================
# СПЕЦИАЛЬНЫЕ ПРАВИЛА ДЛЯ РЕЖИМОВ
# ===========================================
mode_specific:
  # Настройки для режима "auto"
  auto_mode:
    max_risk_pct: 1.5               # Более консервативно в авто-режиме
    max_concurrent_positions: 3      # Меньше позиций в авто
  
  # Настройки для режима "signals"
  signals_mode:
    max_risk_pct: 2.0               # Можно больше риска с ручным контролем
    max_concurrent_positions: 5      # Больше позиций разрешено
  
  # Настройки для тестового режима
  test_mode:
    max_risk_pct: 5.0               # Увеличенные лимиты для тестов
    max_concurrent_positions: 10     # Больше позиций для тестирования

# ===========================================
# ИНТЕГРАЦИЯ С TELEGRAM
# ===========================================
telegram_alerts:
  # Отправлять алерты в Telegram
  enabled: true
  
  # Типы алертов
  send_on_limit_reached: true       # При достижении лимитов
  send_on_circuit_break: true       # При аварийной остановке
  send_daily_summary: true          # Дневная сводка в 23:55 UTC
  send_weekly_summary: true         # Недельная сводка
  
  # Детализация алертов
  include_metrics: true             # Включать метрики в сообщения
  include_recommendations: true     # Включать рекомендации

# ===========================================
# ВОССТАНОВЛЕНИЕ ПОСЛЕ СБОЕВ
# ===========================================
recovery:
  # Автоматическое восстановление
  auto_resume_after_circuit_break: false  # Не возобновлять автоматически
  
  # Условия для возобновления
  resume_conditions:
    # Минимальное время ожидания (минуты)
    min_wait_time: 120
    
    # Требуется ручное подтверждение
    require_manual_confirmation: true
    
    # Сброс счетчиков при возобновлении
    reset_counters_on_resume: false

# ===========================================
# БЭКТЕСТИНГ И СИМУЛЯЦИЯ
# ===========================================
simulation:
  # Использовать эти настройки для бэктестов
  use_for_backtest: true
  
  # Множитель для ускоренного тестирования
  time_multiplier: 1.0              # 1.0 = реальное время
  
  # Игнорировать лимиты в симуляции
  ignore_limits: false              # false = применять все лимиты