# ===========================================
# КОНФИГУРАЦИЯ TELEGRAM БОТА
# Vortex Trading Bot v2.1
# Продакшен-готовая конфигурация
# ===========================================

# ===========================================
# ОСНОВНЫЕ НАСТРОЙКИ БОТА
# ===========================================
bot:
  # Токен бота (получить у @BotFather)
  token: "8072495280:AAGQqCfJS3mRQ3y09pNqN7p-l-AnN3-JAD0"
  
  # Основной чат ID для уведомлений (получить у @userinfobot)
  chat_id: "1753045590"
  
  # Имя бота
  name: "Vortex Trading Bot"
  
  # Описание для команды /start
  description: "Профессиональный торговый бот с управлением рисками и Vortex Bands индикатором"
  
  # Таймаут для запросов (секунды)
  timeout: 30
  
  # Включить/выключить бота
  enabled: true
  
  # Режим отладки (подробные логи)
  debug_mode: false
  
  # Максимальное количество попыток отправки сообщения
  max_retry_attempts: 3

# ===========================================
# ПОЛЬЗОВАТЕЛИ И ПРАВА ДОСТУПА
# ===========================================
users:
  # Список администраторов (могут изменять лимиты рисков и режимы)
  admin_users:
    - "1753045590"  # Замените на ваш Telegram user ID
    # - "987654321"  # Добавьте дополнительных админов
  
  # Список обычных пользователей (только просмотр статистики)
  regular_users:
    - "1753045590"  # Тот же ID может быть и админом и обычным пользователем
  
  # Список заблокированных пользователей
  blocked_users: []
  
  # Максимальное количество пользователей
  max_users: 10

# ===========================================
# НАСТРОЙКИ УВЕДОМЛЕНИЙ
# ===========================================
notifications:
  # Уведомления о торговых операциях
  trade_notifications:
    enabled: true
    include_pnl: true              # Включать прибыль/убыток
    include_signals: true          # Включать торговые сигналы
    include_entry_details: true    # Детали входа в позицию
    include_exit_details: true     # Детали выхода из позиции
    
  # Уведомления о рисках
  risk_notifications:
    enabled: true
    daily_limit_warnings: true      # Предупреждения при приближении к дневным лимитам
    weekly_limit_warnings: true     # Предупреждения при приближении к недельным лимитам
    monthly_limit_warnings: true    # Предупреждения при приближении к месячным лимитам
    circuit_breaker_alerts: true    # Уведомления о срабатывании circuit breaker
    loss_threshold: 0.06           # Порог убытка для алерта (USDT)
    
  # Системные уведомления
  system_notifications:
    enabled: true
    startup_messages: true         # Сообщения о запуске
    shutdown_messages: true        # Сообщения о завершении работы
    error_alerts: true            # Уведомления об ошибках
    connection_alerts: true       # Уведомления о проблемах с подключением
    
  # Статистические уведомления
  statistics:
    daily_report: true            # Ежедневные отчеты
    weekly_report: false          # Еженедельные отчеты (отключено по умолчанию)
    monthly_report: false         # Ежемесячные отчеты (отключено по умолчанию)
    
  # Частота уведомлений
  frequency:
    position_updates: "on_change"    # on_change, hourly, daily, never
    balance_updates: "daily"         # hourly, daily, weekly, never
    risk_summaries: "daily"          # daily, weekly, never
    system_health: "on_error"        # on_error, hourly, daily, never

# ===========================================
# НАСТРОЙКИ КОМАНД
# ===========================================
commands:
  # Основные команды (доступны всем пользователям)
  public_commands:
    - "start"
    - "help"
    - "status"
    - "balance"
    - "positions"
    - "risk"
    - "risk_show"
    
  # Административные команды (только для админов)
  admin_commands:
    - "risk_set"
    - "risk_enable"
    - "risk_reset"
    - "mode"
    - "stop"
    - "restart"
    - "config"
    
  # Команды только для чтения (доступны regular_users)
  readonly_commands:
    - "status"
    - "balance"
    - "positions"
    - "help"
    - "risk_show"
    
  # Скрытые команды (не показываются в /help)
  hidden_commands:
    - "debug"
    - "logs"
    - "system_info"

# ===========================================
# НАСТРОЙКИ БЕЗОПАСНОСТИ
# ===========================================
security:
  # Подтверждение критических операций
  require_confirmation:
    risk_limit_changes: true      # Подтверждение изменения лимитов
    emergency_stops: true         # Подтверждение экстренной остановки
    mode_changes: true           # Подтверждение смены режима работы
    
  # Ограничения по времени (защита от спама)
  rate_limiting:
    enabled: true
    max_commands_per_minute: 10
    cooldown_period: 60          # Секунды блокировки после превышения лимита
    
  # Логирование команд
  command_logging:
    enabled: true
    log_file: "logs/telegram_commands.log"
    include_user_info: true
    include_timestamps: true
    
  # Валидация пользователей
  user_validation:
    check_user_id: true          # Проверять ID пользователя
    whitelist_only: true         # Только пользователи из списков admin/regular

# ===========================================
# ФОРМАТИРОВАНИЕ СООБЩЕНИЙ
# ===========================================
formatting:
  # Использование эмодзи
  use_emojis: true
  
  # Форматирование чисел
  currency_decimals: 4             # Точность для криптовалют
  percentage_decimals: 2           # Точность для процентов
  price_decimals: 6               # Точность для цен
  
  # Языковые настройки
  language: "ru"                  # ru, en
  timezone_display: "UTC"         # Часовой пояс для отображения времени
  date_format: "%Y-%m-%d %H:%M:%S"
  
  # Настройки сообщений
  max_message_length: 4000        # Максимальная длина сообщения
  truncate_long_messages: true    # Обрезать длинные сообщения
  use_markdown: true              # Использовать Markdown разметку
  
  # Шаблоны сообщений
  templates:
    trade_open: "🔵 ОТКРЫТА ПОЗИЦИЯ\n📊 {symbol}\n🎯 {side} | {size} USDT\n💰 Цена: {price}"
    trade_close: "🔴 ЗАКРЫТА ПОЗИЦИЯ\n📊 {symbol}\n💰 P&L: {pnl} USDT\n📈 ROE: {roe}%"
    risk_alert: "⚠️ РИСК АЛЕРТ\n🛡️ {type}\n📊 Текущий убыток: {loss} USDT"

# ===========================================
# НАСТРОЙКИ ИНТЕРФЕЙСА
# ===========================================
interface:
  # Основное меню
  main_menu:
    enabled: true
    layout: "2x3"                # Расположение кнопок: 2 столбца, 3 строки
    persistent: true             # Меню всегда видимо
    
  # Клавиатура
  keyboard:
    enabled: true
    resize_keyboard: true        # Автоматически подстраивать размер
    one_time_keyboard: false     # Не скрывать после использования
    input_field_placeholder: "Выберите команду или введите текст..."
    
  # Быстрые действия
  quick_actions:
    enabled: true
    show_risk_shortcuts: true    # Быстрые кнопки для риск-менеджмента
    show_mode_shortcuts: true    # Быстрые кнопки для смены режима
    
  # Inline кнопки
  inline_buttons:
    enabled: true
    confirmation_buttons: true   # Кнопки подтверждения для критических операций
    navigation_buttons: true     # Кнопки навигации
    
  # Меню быстрого доступа
  quick_menu:
    items:
      - { text: "📊 Статус", command: "status" }
      - { text: "💰 Баланс", command: "balance" }
      - { text: "📈 Позиции", command: "positions" }
      - { text: "🛡️ Риски", command: "risk_show" }
      - { text: "⚙️ Режим", command: "mode" }
      - { text: "🆘 Помощь", command: "help" }

# ===========================================
# ИНТЕГРАЦИЯ С ВНЕШНИМИ СЕРВИСАМИ
# ===========================================
integrations:
  # Webhook для уведомлений (будущая функциональность)
  webhook:
    enabled: false
    url: ""
    secret: ""
    retry_attempts: 3
    
  # Backup уведомления (если Telegram недоступен)
  backup_notifications:
    email:
      enabled: false
      smtp_server: ""
      smtp_port: 587
      username: ""
      password: ""
      recipients: []
      
    # Логирование как backup
    file_backup:
      enabled: true
      log_file: "logs/telegram_backup.log"
      
  # Интеграция с основным приложением
  trading_bot_integration:
    status_check_interval: 30    # Секунды между проверками статуса бота
    auto_reconnect: true         # Автоматическое переподключение
    max_reconnect_attempts: 5    # Максимальное количество попыток переподключения

# ===========================================
# НАСТРОЙКИ МОНИТОРИНГА И ЛОГИРОВАНИЯ
# ===========================================
monitoring:
  # Здоровье системы
  health_checks:
    enabled: true
    interval: 60                 # Секунды между проверками
    alert_on_failure: true       # Алерт при сбоях
    
  # Метрики производительности
  performance_metrics:
    enabled: true
    track_response_time: true    # Отслеживать время ответа
    track_message_count: true    # Отслеживать количество сообщений
    
  # Уведомления о проблемах
  alerts:
    api_errors: true            # Ошибки Telegram API
    network_issues: true        # Проблемы с сетью
    bot_unresponsive: true      # Бот не отвечает

# ===========================================
# НАСТРОЙКИ РАЗРАБОТКИ И ОТЛАДКИ
# ===========================================
development:
  # Режим отладки
  debug_mode: false
  
  # Тестовые пользователи (для тестирования функционала)
  test_users: []
  
  # Подробное логирование
  verbose_logging: false
  
  # Эмуляция задержек (для тестирования)
  simulate_delays: false
  delay_ms: 100
  
  # Тестовый режим (не выполнять реальные операции)
  test_mode: false

# ===========================================
# НАСТРОЙКИ ПРОИЗВОДИТЕЛЬНОСТИ
# ===========================================
performance:
  # Пул соединений
  connection_pool:
    size: 10
    max_overflow: 5
    
  # Кэширование
  caching:
    enabled: true
    ttl: 300                    # Время жизни кэша в секундах
    
  # Асинхронная обработка
  async_processing:
    enabled: true
    max_concurrent_requests: 20
    
  # Ограничения по памяти
  memory_limits:
    max_message_history: 1000   # Максимальное количество сообщений в памяти
    cleanup_interval: 3600      # Интервал очистки в секундах

# ===========================================
# РЕЗЕРВНОЕ КОПИРОВАНИЕ И ВОССТАНОВЛЕНИЕ
# ===========================================
backup:
  # Автоматическое резервное копирование настроек
  auto_backup:
    enabled: true
    interval: 86400             # Раз в день (секунды)
    backup_directory: "backups/telegram"
    max_backups: 7              # Хранить последние 7 бэкапов
    
  # Восстановление после сбоя
  disaster_recovery:
    auto_restore: true
    fallback_config: "telegram_fallback.yaml"